[package]
name           = "azure_sdk_for_rust"
version        = "0.10.0"
description    = "Rust wrappers around Microsoft Azure REST APIs"
readme         = "README.md"
authors        = ["Francesco Cogno <francesco.cogno@outlook.com>", "Max Gortman <mgortman@microsoft.com>", "Dong Liu <doliu@microsoft.com>"]
license        = "Apache-2.0"
repository     = "https://github.com/MindFlavor/AzureSDKForRust"
documentation  = "http://mindflavor.github.io/AzureSDKForRust/azure_sdk_for_rust/index.html"
homepage       = "https://github.com/MindFlavor/AzureSDKForRust"

keywords       = ["sdk", "azure", "rest", "iot", "cloud"]
categories     = ["api-bindings"]

[dependencies]
ring         = "0.11.0"
md5          = "0.3.7"
RustyXML     = "0.1.1"
base64       = "0.9.2"
chrono       = "0.4.2"
env_logger   = "0.5.10"
futures      = "0.1.21"
http         = "0.1"
hyper        = "0.12"
hyper-tls    = "0.2"
log          = "0.4.2"
mime         = "0.3.7"
quick-error  = "1.2.2"
serde        = "1.0.66"
serde_derive = "1.0.66"
serde_json   = "1.0.19"
serde-xml-rs = "0.2.1"
time         = "0.1.40"
url          = "1.7.0"
uuid         = { version = "0.6", features = ["v4"] }
smallvec     = { version = "0.6", features = ["serde"] }
bytes        = "0.4"

[dev-dependencies]
tokio-core   = "0.1.12"

[features]
test_e2e       = []
